name: libzt_flutter
description: "ZeroTier Socket API (libzt) ffi bindings for Dart as a Flutter plugin."
version: 0.0.3
homepage: null

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

dependencies:
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffigen: ^13.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
